#include <SI_EFM8BB1_Register_Enums.h>
#include <SI_EFM8BB1_Defs.h>

#define WD_DISABLE_A 0xDE
#define WD_DISABLE_B 0xAD

#define SYSCLOCK 24500000u
#define SYS_PRESCALER 8u

#define TIMER3_PRESCALER 12u
#define TIMER3_BASE_CLOCK (SYSCLOCK / (SYS_PRESCALER * TIMER3_PRESCALER))
#define TIMER3_TARGET_HZ 10u
#define TIMER3_SIZE 65536u
#define TIMER3_RELOAD (TIMER3_SIZE - (TIMER3_BASE_CLOCK / TIMER3_TARGET_HZ))

#define BYTE_SIZE 8u

#define LED0 P1_B4

void SiLabs_Startup (void)
{
  // Erre nincs konstans az Enumsban.
  WDTCN = WD_DISABLE_A;
  WDTCN = WD_DISABLE_B;

  XBR2 |= XBR2_XBARE__ENABLED;

  P1MDOUT |= P1MASK_B4__COMPARED;

  IE_EA = 1;
  EIE1 |= EIE1_ET3__ENABLED;

  TMR3CN0 |= TMR3CN0_TR3__RUN;
  TMR3CN0 &= ~TMR3CN0_T3SPLIT__BMASK;
  TMR3CN0 &= ~TMR3CN0_T3XCLK__BMASK;

  TMR3RLH = TIMER3_RELOAD >> BYTE_SIZE;
  TMR3RLL = TIMER3_RELOAD;
}

int main (void)
{
  while (1) {}
}

void timer3_interrupt (void) interrupt TIMER3_IRQn
{
  TMR3CN0 &= ~TMR3CN0_TF3H__BMASK;

  LED0 = ~LED0;
}
