//=========================================================
// src/miclab-04-01_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

#define RESOLUTION 1024.0f
#define REFERENCE_VOLTAGE_MV 3300u
#define FIX_RESISTOR 2120u
#define THERMISTOR_TABLE_SIZE 7

volatile uint16_t adc_value = 0;
volatile uint16_t voltage_mv = 0;

uint16_t thermistor_resistances[THERMISTOR_TABLE_SIZE] = {
    32650u,
    19900u,
    12490u,
    10000u,
    8057u,
    5327u,
    0u, //3603u,
};

uint16_t thermistor_temperatures[THERMISTOR_TABLE_SIZE] = {
    0u,
    10u,
    20u,
    25u,
    30u,
    40u,
    50u,
};

float thermistor_linearization[THERMISTOR_TABLE_SIZE] = {
    0.000784f,
    0.001349f,
    0.002008f,
    0.002573f,
    0.003663f,
    0.005800f,
    0.008968f,
};

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();

  while (1)
  {
      float ratio_fix;
      float ratio_thermistor;
      float total_resistance;
      uint16_t thermistor_resistance;

      uint16_t base_temp = 0;
      uint16_t base_resistance = 0;
      float linearization_coefficient = 0;
      uint16_t temp = 0u;

      uint16_t i = 0;

      IE_EA = 0;

      ratio_fix = adc_value / RESOLUTION;
      ratio_thermistor = 1 - ratio_fix;
      total_resistance = FIX_RESISTOR / ratio_thermistor;
      thermistor_resistance = ratio_fix * total_resistance;

      for (i = 0; i < THERMISTOR_TABLE_SIZE; i++)
      {
          if (thermistor_resistance > thermistor_resistances[i]) {
              base_resistance = thermistor_resistances[i];
              base_temp = thermistor_temperatures[i];
              linearization_coefficient = thermistor_linearization[i];
              break;
          }
      }

      temp = base_temp + (thermistor_resistance - base_resistance) * linearization_coefficient;

      IE_EA = 1;
  }
}
