//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>

#define ONBOARD_LED P1_B4
#define ONBOARD_BTN P0_B2
#define LED_ENABLE 0
#define LED_DISABLE 1
#define MAGIC_WAIT 3795
#define ALLOWED_DELAY 200
#define COUNTER_RESET 0

enum {
	WAIT_FOR_LED, // Waiting for LED to turn on (counting to 3795ms)
	LED_ON, // LED is on, waiting for button press
	LED_OFF // LED turned off after button press
} State;

extern uint16_t globalCounter = 0;
extern uint16_t globalState = WAIT_FOR_LED;

//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{
	switch (globalState)
	{
		// This is the initial state
		case WAIT_FOR_LED:
			globalCounter++;

			if (globalCounter == MAGIC_WAIT)
			{
				globalState = LED_ON;
				globalCounter = COUNTER_RESET;
				ONBOARD_LED = LED_ENABLE;
			}
			else
			{
				ONBOARD_LED = LED_DISABLE;
			}

			break;
		// This is the speed testing part
		case LED_ON:
			if (globalCounter > ALLOWED_DELAY) {
				break;
			}

			globalCounter++;

			if (!ONBOARD_BTN)
			{
				globalState = LED_OFF;
				ONBOARD_LED = LED_DISABLE;
			}

			break;
		// This is the win condition
		case LED_OFF:
		default:
			break;
	}
}

