//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#define ONBOARD_LED P1_B4
#define ONBOARD_BTN P0_B2

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------

extern uint8_t tim;

SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{
	if (!ONBOARD_BTN)
	{
		tim++;
	}
	else
	{
		tim = 0;
	}
}

