//=========================================================
// src/miclab-04-01_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

#define RESOLUTION 1024.0f
#define REFERENCE_VOLTAGE_MV 3300u
#define FIX_RESISTOR 2120u


volatile uint16_t adc_value = 0;
volatile uint16_t voltage_mv = 0;

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();

  while (1)
  {
      float ratio_fix;
      float ratio_thermistor;
      float total_resistance;
      uint16_t thermistor_resistance;

      IE_EA = 0;

      ratio_fix = adc_value / RESOLUTION;
      ratio_thermistor = 1 - ratio_fix;
      total_resistance = FIX_RESISTOR / ratio_thermistor;
      thermistor_resistance = ratio_fix * total_resistance;

      IE_EA = 1;
  }
}
